import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { useQuery } from "@tanstack/react-query";
import { EmergencyAlert } from "@/components/EmergencyAlert";
import { Button } from "@/components/ui/button";
import { Share2, Copy, ChevronDown, ChevronUp, Loader2 } from "lucide-react";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

type Biomarker = {
  name: string;
  value: number;
  unit: string;
  reference_range: string;
  status: "normal" | "borderline" | "deranged-low" | "deranged-high" | "critical";
  explanation: string;
  why_it_matters: string;
};

type DietaryPlan = {
  foods_to_increase: Array<{ name: string; local_name: string; benefit: string; preparation_tip: string }>;
  foods_to_reduce: Array<{ name: string; local_name: string; reason: string }>;
  foods_to_avoid: Array<{ name: string; local_name: string; reason: string }>;
  meal_suggestions: Array<{ meal: string; description: string }>;
};

const STATUS_COLORS: Record<string, string> = {
  normal: "bg-secondary/20 text-secondary border-secondary/30",
  borderline: "bg-harvest-gold/20 text-harvest-gold border-harvest-gold/30",
  "deranged-low": "bg-destructive/20 text-destructive border-destructive/30",
  "deranged-high": "bg-destructive/20 text-destructive border-destructive/30",
  critical: "bg-destructive text-destructive-foreground border-destructive",
};

const STATUS_LABELS: Record<string, string> = {
  normal: "Normal",
  borderline: "Borderline",
  "deranged-low": "Low",
  "deranged-high": "High",
  critical: "Critical",
};

const ResultReport = () => {
  const { id } = useParams<{ id: string }>();
  const { user } = useAuth();
  const navigate = useNavigate();
  const [showEmergency, setShowEmergency] = useState(false);
  const [expandedBiomarker, setExpandedBiomarker] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<"results" | "diet" | "checklist">("results");

  const { data: result, isLoading } = useQuery({
    queryKey: ["lab-result", id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("lab_results")
        .select("*")
        .eq("id", id!)
        .eq("user_id", user!.id)
        .single();
      if (error) throw error;
      return data;
    },
    enabled: !!id && !!user,
    refetchInterval: (query) => {
      const data = query.state.data;
      return data?.status === "processing" ? 3000 : false;
    },
  });

  useEffect(() => {
    if (result?.has_critical_alert) setShowEmergency(true);
  }, [result?.has_critical_alert]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="w-8 h-8 animate-spin text-accent" />
      </div>
    );
  }

  if (!result) {
    return (
      <div className="px-5 pt-12 text-center">
        <p className="text-muted-foreground">Result not found.</p>
        <Button onClick={() => navigate("/")} variant="outline" className="mt-4">
          Go Home
        </Button>
      </div>
    );
  }

  if (result.status === "processing") {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen px-6">
        <Loader2 className="w-12 h-12 text-accent animate-spin mb-6" />
        <p className="font-display text-lg font-semibold">Analyzing your results...</p>
        <p className="text-muted-foreground text-body-sm mt-2 text-center">
          Our AI is reading your lab result and preparing your diet plan.
        </p>
      </div>
    );
  }

  if (result.status === "failed") {
    return (
      <div className="px-5 pt-12 text-center">
        <p className="text-destructive font-semibold text-body">We couldn't read your lab result</p>
        <p className="text-muted-foreground text-body-sm mt-2">
          Please try uploading a clearer image or PDF.
        </p>
        <Button onClick={() => navigate("/upload")} className="mt-4 bg-accent text-accent-foreground">
          Try Again
        </Button>
      </div>
    );
  }

  const biomarkers = (result.biomarkers as Biomarker[] | null) || [];
  const dietaryPlan = result.dietary_plan as DietaryPlan | null;
  const checklist = (result.consultation_checklist as string[] | null) || [];
  const criticalAlerts = (result.critical_alerts as any[] | null) || [];

  if (showEmergency && criticalAlerts.length > 0) {
    return (
      <EmergencyAlert
        alerts={criticalAlerts}
        onAcknowledge={() => setShowEmergency(false)}
      />
    );
  }

  const shareChecklist = async () => {
    const text = `My BioGuide Consultation Checklist:\n\n${checklist
      .map((q, i) => `${i + 1}. ${q}`)
      .join("\n")}\n\n— Generated by BioGuide`;

    if (navigator.share) {
      try {
        await navigator.share({ text, title: "My Consultation Checklist" });
      } catch {}
    } else {
      await navigator.clipboard.writeText(text);
      toast.success("Checklist copied to clipboard!");
    }
  };

  return (
    <div className="px-5 pt-6 pb-4 max-w-lg mx-auto">
      <button onClick={() => navigate(-1)} className="text-muted-foreground text-body-sm mb-4 touch-target">
        ← Back
      </button>

      <h1 className="font-display text-2xl font-bold mb-1">Your Lab Report</h1>
      <p className="text-muted-foreground text-body-sm mb-6">
        {new Date(result.upload_date).toLocaleDateString("en-NG", {
          day: "numeric",
          month: "long",
          year: "numeric",
        })}
      </p>

      {/* Tabs */}
      <div className="flex gap-2 mb-6 overflow-x-auto pb-1">
        {(["results", "diet", "checklist"] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={cn(
              "px-5 py-3 rounded-xl font-semibold text-body-sm whitespace-nowrap touch-target transition-colors",
              activeTab === tab
                ? "bg-primary text-primary-foreground"
                : "bg-card border border-border text-foreground"
            )}
          >
            {tab === "results" ? "Biomarkers" : tab === "diet" ? "Diet Plan" : "Doctor Questions"}
          </button>
        ))}
      </div>

      {/* Biomarkers Tab */}
      {activeTab === "results" && (
        <div className="space-y-3">
          {biomarkers.map((b) => (
            <div key={b.name} className="bg-card rounded-xl border border-border overflow-hidden">
              <button
                onClick={() => setExpandedBiomarker(expandedBiomarker === b.name ? null : b.name)}
                className="w-full p-4 flex items-center justify-between touch-target"
              >
                <div className="text-left">
                  <p className="font-semibold text-body">{b.name}</p>
                  <p className="text-body-sm text-muted-foreground">
                    {b.value} {b.unit} <span className="text-xs">(Ref: {b.reference_range})</span>
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <span className={cn("px-3 py-1 rounded-full text-xs font-bold border", STATUS_COLORS[b.status])}>
                    {STATUS_LABELS[b.status]}
                  </span>
                  {expandedBiomarker === b.name ? (
                    <ChevronUp className="w-5 h-5 text-muted-foreground" />
                  ) : (
                    <ChevronDown className="w-5 h-5 text-muted-foreground" />
                  )}
                </div>
              </button>
              {expandedBiomarker === b.name && (
                <div className="px-4 pb-4 border-t border-border pt-3 space-y-2 animate-slide-up">
                  <div>
                    <p className="text-xs font-bold text-muted-foreground uppercase tracking-wide">What this means</p>
                    <p className="text-body-sm">{b.explanation}</p>
                  </div>
                  <div>
                    <p className="text-xs font-bold text-muted-foreground uppercase tracking-wide">Why it matters</p>
                    <p className="text-body-sm">{b.why_it_matters}</p>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* Diet Tab */}
      {activeTab === "diet" && dietaryPlan && (
        <div className="space-y-6">
          {/* Foods to Increase */}
          {dietaryPlan.foods_to_increase?.length > 0 && (
            <div>
              <h3 className="font-display text-lg font-bold text-secondary mb-3">✅ Foods for You</h3>
              <div className="space-y-3">
                {dietaryPlan.foods_to_increase.map((f, i) => (
                  <div key={i} className="bg-secondary/10 rounded-xl p-4 border border-secondary/20">
                    <p className="font-bold text-body">{f.name}</p>
                    {f.local_name && <p className="text-body-sm text-secondary italic">"{f.local_name}"</p>}
                    <p className="text-body-sm text-muted-foreground mt-1">{f.benefit}</p>
                    {f.preparation_tip && (
                      <p className="text-xs text-muted-foreground mt-1">💡 {f.preparation_tip}</p>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Foods to Reduce */}
          {dietaryPlan.foods_to_reduce?.length > 0 && (
            <div>
              <h3 className="font-display text-lg font-bold text-harvest-gold mb-3">⚠️ Eat Less Of</h3>
              <div className="space-y-3">
                {dietaryPlan.foods_to_reduce.map((f, i) => (
                  <div key={i} className="bg-harvest-gold/10 rounded-xl p-4 border border-harvest-gold/20">
                    <p className="font-bold text-body">{f.name}</p>
                    {f.local_name && <p className="text-body-sm italic text-harvest-gold">"{f.local_name}"</p>}
                    <p className="text-body-sm text-muted-foreground mt-1">{f.reason}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Foods to Avoid */}
          {dietaryPlan.foods_to_avoid?.length > 0 && (
            <div>
              <h3 className="font-display text-lg font-bold text-destructive mb-3">🚫 Avoid These</h3>
              <div className="space-y-3">
                {dietaryPlan.foods_to_avoid.map((f, i) => (
                  <div key={i} className="bg-destructive/10 rounded-xl p-4 border border-destructive/20">
                    <p className="font-bold text-body">{f.name}</p>
                    {f.local_name && <p className="text-body-sm italic text-destructive">"{f.local_name}"</p>}
                    <p className="text-body-sm text-muted-foreground mt-1">{f.reason}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Meal Suggestions */}
          {dietaryPlan.meal_suggestions?.length > 0 && (
            <div>
              <h3 className="font-display text-lg font-bold mb-3">🍽️ Meal Ideas</h3>
              <div className="space-y-3">
                {dietaryPlan.meal_suggestions.map((m, i) => (
                  <div key={i} className="bg-card rounded-xl p-4 border border-border">
                    <p className="font-bold text-body">{m.meal}</p>
                    <p className="text-body-sm text-muted-foreground">{m.description}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      {/* Checklist Tab */}
      {activeTab === "checklist" && (
        <div>
          <p className="text-muted-foreground text-body-sm mb-4">
            Questions to bring to your next doctor's appointment:
          </p>
          <div className="space-y-3 mb-6">
            {checklist.map((q, i) => (
              <div key={i} className="bg-card rounded-xl p-4 border border-border flex gap-3">
                <span className="w-7 h-7 rounded-full bg-accent/20 text-accent font-bold text-sm flex items-center justify-center flex-shrink-0">
                  {i + 1}
                </span>
                <p className="text-body-sm">{q}</p>
              </div>
            ))}
          </div>
          {checklist.length > 0 && (
            <div className="flex gap-3">
              <Button onClick={shareChecklist} className="flex-1 h-12 rounded-xl bg-accent text-accent-foreground touch-target">
                <Share2 className="w-4 h-4 mr-2" /> Share
              </Button>
              <Button
                onClick={async () => {
                  const text = checklist.map((q, i) => `${i + 1}. ${q}`).join("\n");
                  await navigator.clipboard.writeText(text);
                  toast.success("Copied!");
                }}
                variant="outline"
                className="flex-1 h-12 rounded-xl touch-target"
              >
                <Copy className="w-4 h-4 mr-2" /> Copy
              </Button>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default ResultReport;
