import { useState } from "react";
import { ChecklistItem } from "./types";
import { cn } from "@/lib/utils";
import { Share2, Copy, ChevronDown, ChevronUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

interface ChecklistTabProps {
  checklist: ChecklistItem[];
}

const PRIORITY_COLORS: Record<string, string> = {
  high: "bg-destructive/20 text-destructive border-destructive/30",
  medium: "bg-harvest-gold/20 text-harvest-gold border-harvest-gold/30",
  low: "bg-secondary/20 text-secondary border-secondary/30",
};

function isStructured(item: ChecklistItem): item is { question: string; context: string; priority: string } {
  return typeof item === "object" && "question" in item;
}

export const ChecklistTab = ({ checklist }: ChecklistTabProps) => {
  const [expandedQ, setExpandedQ] = useState<number | null>(null);

  const getQuestionText = (item: ChecklistItem) => isStructured(item) ? item.question : item;

  const shareChecklist = async () => {
    const text = `My BioGuide Consultation Checklist:\n\n${checklist
      .map((q, i) => `${i + 1}. ${getQuestionText(q)}`)
      .join("\n")}\n\n— Generated by BioGuide`;

    if (navigator.share) {
      try { await navigator.share({ text, title: "My Consultation Checklist" }); } catch {}
    } else {
      await navigator.clipboard.writeText(text);
      toast.success("Checklist copied to clipboard!");
    }
  };

  const copyChecklist = async () => {
    const text = checklist.map((q, i) => `${i + 1}. ${getQuestionText(q)}`).join("\n");
    await navigator.clipboard.writeText(text);
    toast.success("Copied!");
  };

  // Sort structured items by priority
  const sorted = [...checklist].sort((a, b) => {
    if (!isStructured(a) || !isStructured(b)) return 0;
    const order = { high: 0, medium: 1, low: 2 };
    return (order[a.priority] ?? 2) - (order[b.priority] ?? 2);
  });

  return (
    <div>
      <p className="text-muted-foreground text-body-sm mb-4">
        Questions to bring to your next doctor's appointment:
      </p>
      <div className="space-y-3 mb-6">
        {sorted.map((q, i) => {
          const structured = isStructured(q);
          const questionText = getQuestionText(q);

          return (
            <div key={i} className="bg-card rounded-xl border border-border overflow-hidden">
              <button
                onClick={() => structured ? setExpandedQ(expandedQ === i ? null : i) : undefined}
                className={cn("w-full p-4 flex gap-3 text-left", structured && "touch-target")}
              >
                <span className="w-7 h-7 rounded-full bg-accent/20 text-accent font-bold text-sm flex items-center justify-center flex-shrink-0">
                  {i + 1}
                </span>
                <div className="flex-1">
                  <p className="text-body-sm">{questionText}</p>
                </div>
                <div className="flex items-center gap-2 flex-shrink-0">
                  {structured && (
                    <span className={cn("px-2 py-0.5 rounded-full text-[10px] font-bold uppercase border", PRIORITY_COLORS[q.priority])}>
                      {q.priority}
                    </span>
                  )}
                  {structured && (
                    expandedQ === i ? <ChevronUp className="w-4 h-4 text-muted-foreground" /> : <ChevronDown className="w-4 h-4 text-muted-foreground" />
                  )}
                </div>
              </button>
              {structured && expandedQ === i && (
                <div className="px-4 pb-4 border-t border-border pt-3 animate-slide-up">
                  <p className="text-xs font-bold text-muted-foreground uppercase tracking-wide mb-1">Why this matters</p>
                  <p className="text-body-sm text-muted-foreground">{q.context}</p>
                </div>
              )}
            </div>
          );
        })}
      </div>
      {checklist.length > 0 && (
        <div className="flex gap-3">
          <Button onClick={shareChecklist} className="flex-1 h-12 rounded-xl bg-accent text-accent-foreground touch-target">
            <Share2 className="w-4 h-4 mr-2" /> Share
          </Button>
          <Button onClick={copyChecklist} variant="outline" className="flex-1 h-12 rounded-xl touch-target">
            <Copy className="w-4 h-4 mr-2" /> Copy
          </Button>
        </div>
      )}
    </div>
  );
};
