import { useState } from "react";
import { ChecklistItem, ChecklistItemPidgin, Language } from "./types";
import { cn } from "@/lib/utils";
import { Share2, Copy, ChevronDown, ChevronUp, Loader2, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

interface ChecklistTabProps {
  checklist: ChecklistItem[];
  checklistPidgin: ChecklistItemPidgin[] | null;
  language: Language;
  status?: "pending" | "done" | "failed";
  onRegenerate?: () => void;
  regenerating?: boolean;
}

const PRIORITY_COLORS: Record<string, string> = {
  high: "bg-destructive/20 text-destructive border-destructive/30",
  medium: "bg-harvest-gold/20 text-harvest-gold border-harvest-gold/30",
  low: "bg-secondary/20 text-secondary border-secondary/30",
};

function isStructured(item: ChecklistItem): item is { question: string; context: string; priority: "high" | "medium" | "low" } {
  return typeof item === "object" && "question" in item;
}

export const ChecklistTab = ({ checklist, checklistPidgin, language, status, onRegenerate, regenerating }: ChecklistTabProps) => {
  const [expandedQ, setExpandedQ] = useState<number | null>(null);
  const isPidgin = language === "pidgin";

  // Pending state — checklist still generating
  if (status === "pending" && checklist.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <Loader2 className="w-8 h-8 animate-spin text-secondary-foreground mb-3" />
        <p className="text-body-sm font-semibold text-foreground">
          {isPidgin ? "Dey prepare your doctor questions…" : "Generating your doctor's questions…"}
        </p>
        <p className="text-xs text-muted-foreground mt-1">
          {isPidgin ? "Small time, e go ready." : "This usually takes a few seconds."}
        </p>
      </div>
    );
  }

  // Failed state — offer regenerate
  if (status === "failed" && checklist.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <p className="text-body-sm font-semibold text-foreground mb-2">
          {isPidgin ? "We no fit prepare your questions this time." : "We couldn't prepare your doctor's questions this time."}
        </p>
        <p className="text-xs text-muted-foreground mb-4">
          {isPidgin ? "Try am again." : "You can try regenerating them now."}
        </p>
        {onRegenerate && (
          <Button onClick={onRegenerate} disabled={regenerating} className="h-11 rounded-xl bg-accent text-accent-foreground touch-target">
            {regenerating ? (
              <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> {isPidgin ? "Dey try…" : "Regenerating…"}</>
            ) : (
              <><RefreshCw className="w-4 h-4 mr-2" /> {isPidgin ? "Try Am Again" : "Regenerate"}</>
            )}
          </Button>
        )}
      </div>
    );
  }

  const getQuestionText = (item: ChecklistItem, index: number) => {
    if (isPidgin && checklistPidgin?.[index]) return checklistPidgin[index].question;
    return isStructured(item) ? item.question : item;
  };

  const getContext = (item: ChecklistItem, index: number) => {
    if (isPidgin && checklistPidgin?.[index]) return checklistPidgin[index].context;
    return isStructured(item) ? item.context : "";
  };

  const shareChecklist = async () => {
    const text = `${isPidgin ? "My VeriDIA Doctor Questions:" : "My VeriDIA Consultation Checklist:"}\n\n${checklist
      .map((q, i) => `${i + 1}. ${getQuestionText(q, i)}`)
      .join("\n")}\n\n— Generated by VeriDIA`;

    if (navigator.share) {
      try { await navigator.share({ text, title: "My Consultation Checklist" }); } catch {}
    } else {
      await navigator.clipboard.writeText(text);
      toast.success(isPidgin ? "E don copy!" : "Checklist copied to clipboard!");
    }
  };

  const copyChecklist = async () => {
    const text = checklist.map((q, i) => `${i + 1}. ${getQuestionText(q, i)}`).join("\n");
    await navigator.clipboard.writeText(text);
    toast.success(isPidgin ? "E don copy!" : "Copied!");
  };

  const sorted = [...checklist].sort((a, b) => {
    if (!isStructured(a) || !isStructured(b)) return 0;
    const order = { high: 0, medium: 1, low: 2 };
    return (order[a.priority] ?? 2) - (order[b.priority] ?? 2);
  });

  return (
    <div>
      <p className="text-muted-foreground text-body-sm mb-4">
        {isPidgin
          ? "Questions wey you go carry go meet doctor:"
          : "Questions to bring to your next doctor's appointment:"}
      </p>
      <div className="space-y-3 mb-6">
        {sorted.map((q, i) => {
          const structured = isStructured(q);
          const questionText = getQuestionText(q, i);
          const context = getContext(q, i);

          return (
            <div key={i} className="bg-card rounded-xl border border-border overflow-hidden">
              <button
                onClick={() => structured ? setExpandedQ(expandedQ === i ? null : i) : undefined}
                className={cn("w-full p-4 flex gap-3 text-left", structured && "touch-target")}
              >
                <span className="w-7 h-7 rounded-full bg-accent/20 text-secondary-foreground font-bold text-sm flex items-center justify-center flex-shrink-0">
                  {i + 1}
                </span>
                <div className="flex-1">
                  <p className="text-body-sm">{questionText}</p>
                </div>
                <div className="flex items-center gap-2 flex-shrink-0">
                  {structured && (
                    <span className={cn("px-2 py-0.5 rounded-full text-[10px] font-bold uppercase border", PRIORITY_COLORS[q.priority])}>
                      {q.priority}
                    </span>
                  )}
                  {structured && (
                    expandedQ === i ? <ChevronUp className="w-4 h-4 text-muted-foreground" /> : <ChevronDown className="w-4 h-4 text-muted-foreground" />
                  )}
                </div>
              </button>
              {structured && expandedQ === i && context && (
                <div className="px-4 pb-4 border-t border-border pt-3 animate-slide-up">
                  <p className="text-xs font-bold text-muted-foreground uppercase tracking-wide mb-1">
                    {isPidgin ? "Why e matter" : "Why this matters"}
                  </p>
                  <p className="text-body-sm text-muted-foreground">{context}</p>
                </div>
              )}
            </div>
          );
        })}
      </div>
      {checklist.length > 0 && (
        <div className="flex gap-3">
          <Button onClick={shareChecklist} className="flex-1 h-12 rounded-xl bg-accent text-accent-foreground touch-target">
            <Share2 className="w-4 h-4 mr-2" /> {isPidgin ? "Share Am" : "Share"}
          </Button>
          <Button onClick={copyChecklist} variant="outline" className="flex-1 h-12 rounded-xl touch-target">
            <Copy className="w-4 h-4 mr-2" /> {isPidgin ? "Copy Am" : "Copy"}
          </Button>
        </div>
      )}
    </div>
  );
};
