import { Biomarker } from "./types";
import { cn } from "@/lib/utils";
import { Activity, TrendingUp, AlertTriangle, CheckCircle2, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

interface SummaryTabProps {
  biomarkers: Biomarker[];
  aiSummary: string | null;
  uploadDate: string;
}

export const SummaryTab = ({ biomarkers, aiSummary, uploadDate }: SummaryTabProps) => {
  const normal = biomarkers.filter(b => b.status === "normal").length;
  const borderline = biomarkers.filter(b => b.status === "borderline").length;
  const abnormal = biomarkers.filter(b => ["deranged-low", "deranged-high", "critical"].includes(b.status)).length;
  const total = biomarkers.length;
  const healthScore = total > 0 ? Math.round((normal / total) * 100) : 0;

  const shareReport = async () => {
    const text = `BioGuide Health Summary (${new Date(uploadDate).toLocaleDateString("en-NG")})\n\n${aiSummary || ""}\n\n✅ Normal: ${normal} | ⚠️ Borderline: ${borderline} | 🔴 Abnormal: ${abnormal}\n\n— Generated by BioGuide`;
    if (navigator.share) {
      try { await navigator.share({ text, title: "My BioGuide Report" }); } catch {}
    } else {
      await navigator.clipboard.writeText(text);
      toast.success("Report copied to clipboard!");
    }
  };

  return (
    <div className="space-y-5">
      {/* Health Score Card */}
      <div className="bg-card rounded-2xl border border-border p-5">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-full bg-accent/20 flex items-center justify-center">
            <Activity className="w-5 h-5 text-accent" />
          </div>
          <div>
            <p className="font-display font-bold text-lg">Health Snapshot</p>
            <p className="text-muted-foreground text-xs">{total} biomarkers analyzed</p>
          </div>
        </div>

        {/* Score Ring */}
        <div className="flex items-center justify-center my-4">
          <div className="relative w-32 h-32">
            <svg className="w-full h-full -rotate-90" viewBox="0 0 120 120">
              <circle cx="60" cy="60" r="50" fill="none" stroke="hsl(var(--muted))" strokeWidth="10" />
              <circle
                cx="60" cy="60" r="50" fill="none"
                stroke={healthScore >= 70 ? "hsl(var(--secondary))" : healthScore >= 40 ? "hsl(var(--harvest-gold))" : "hsl(var(--destructive))"}
                strokeWidth="10" strokeLinecap="round"
                strokeDasharray={`${healthScore * 3.14} 314`}
              />
            </svg>
            <div className="absolute inset-0 flex flex-col items-center justify-center">
              <span className="font-display text-3xl font-bold">{healthScore}%</span>
              <span className="text-xs text-muted-foreground">Normal</span>
            </div>
          </div>
        </div>

        {/* Status Breakdown */}
        <div className="grid grid-cols-3 gap-3 mt-4">
          <div className="text-center p-3 rounded-xl bg-secondary/10 border border-secondary/20">
            <CheckCircle2 className="w-5 h-5 text-secondary mx-auto mb-1" />
            <p className="font-bold text-lg">{normal}</p>
            <p className="text-xs text-muted-foreground">Normal</p>
          </div>
          <div className="text-center p-3 rounded-xl bg-harvest-gold/10 border border-harvest-gold/20">
            <TrendingUp className="w-5 h-5 text-harvest-gold mx-auto mb-1" />
            <p className="font-bold text-lg">{borderline}</p>
            <p className="text-xs text-muted-foreground">Borderline</p>
          </div>
          <div className="text-center p-3 rounded-xl bg-destructive/10 border border-destructive/20">
            <AlertTriangle className="w-5 h-5 text-destructive mx-auto mb-1" />
            <p className="font-bold text-lg">{abnormal}</p>
            <p className="text-xs text-muted-foreground">Abnormal</p>
          </div>
        </div>
      </div>

      {/* AI Summary */}
      {aiSummary && (
        <div className="bg-card rounded-2xl border border-border p-5">
          <p className="text-xs font-bold text-muted-foreground uppercase tracking-wide mb-2">AI Health Summary</p>
          <p className="text-body-sm leading-relaxed">{aiSummary}</p>
        </div>
      )}

      {/* Share Button */}
      <Button onClick={shareReport} className="w-full h-12 rounded-xl bg-accent text-accent-foreground touch-target">
        <Share2 className="w-4 h-4 mr-2" /> Share Report Summary
      </Button>
    </div>
  );
};
